name: Lint Code Base

on:
  push:
    branches:
      - go

jobs:
  build:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: go
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
