name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: npm install
        run: npm install
      - name: types
        run: npm run type-check
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
